name = "kv"
main = "./src/index.js" 
account_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
compatibility_date = "2024-11-11"
compatibility_flags = [ "nodejs_compat" ]
[[kv_namespaces]]
binding = "cache_dev"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
preview_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
